# Generated by Django 5.0.6 on 2024-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='tinker',
            field=models.CharField(max_length=10),
        ),
    ]
