# Generated by Django 5.0.6 on 2024-06-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_stock_tinker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='tinker',
            new_name='ticker',
        ),
    ]
